### ISSUE TITLE
Server rendering bug

### ISSUE THREAD

**Issue by SPAHI4** [gorangajic/react-svg-morph#3]
`ReferenceError: window is not defined`

**Comment by gorangajic** [comment]
fixed https://github.com/gorangajic/react-svg-morph/commit/dfc90c4da0bd881c23b2e1de2e39b0018aed10e2

published on npm v0.1.3

**Comment by evenchange4** [comment]
Still ran into this problem at version `v0.1.6`.

**Comment by gorangajic** [comment]
try now https://github.com/gorangajic/react-svg-morph/commit/0535555f702b0cee732cdde81dc24e8ea5d1b96f

**Comment by evenchange4** [comment]
@gorangajic Thanks for the quick fix. 
I try `v0.1.7` but it still does not work correctly.
I send a PR #11 to fix that. Please review it. Thanks! 😉
